cd data
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/tracings.json
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/drawings.json
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/drawings_registered.json
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/images.zip
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/density.zip
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/png.zip
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/svg.zip
wget http://tracer.cs.yale.edu/tracing-vs-freehand/data/npr_thresh.zip
wget https://cislab.hkust-gz.edu.cn/projects/tracing-vs-freehand/data/model.zip
unzip '*.zip'
rm *.zip
